server:
  port: 8080
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 1GB
    context-path: /boot

file:
  staticAccessPath: /file/**
  uploadFolder: /app/upload/
  uploadImage: image/

spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          address: "redis://127.0.0.1:6379"
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
    host: localhost
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        minIdle: 5
        maxIdle: 200
        maxWait: 10000
        maxActive: 8
  jackson:
    default-property-inclusion: non_null

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeoutweb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: chenxiang

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration

mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cx.springboot02.mapper: debug
