#server.port=8080
#spring.main.banner-mode=off
#spring.banner.image.location=demo.png

#logging.level.root=info
#server.port=8080
#type=com.alibaba.druid.pool.DruidDataSource
#spring.thymeleaf.cache=false
#mybatis.mapper-locations=classpath:mapper/*.xml

rocketmq.producer.isOnOff=off
rocketmq.producer.groupName=${spring.application.name}
rocketmq.producer.namesrvAddr=127.0.0.1:9876
rocketmq.producer.maxMessageSize = 4096
rocketmq.producer.sendMsgTimeOut=3000
rocketmq.producer.retryTimesWhenSendFailed=2

# RocketMQ NameServer地址
rocketmq.namesrv-addr=127.0.0.1:9876

# IK分词器词库路径
ik.path=/app/upload/ik.dic
